name: Analytics
on: push

jobs:
  pester-test:
    name: validate aliasses
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Validate Kusto Aliasses
        uses: SecureHats/kusto-alias@v0.1.0-alpha
        with:
          filesPath: templates
          logLevel: Detailed
